### ISSUE TITLE
Make a JPA module with deltaspike-jpa, deltaspike-data, pax-jpa

### ISSUE THREAD

**Issue by Tcharl** [OsgiliathEnterprise/net.osgiliath.parent#46]
As the migration to pax-jdbc has been done, it could be nice to replace (or add a new) the blueprint/spring-data based jpa module by a deltaspike-jpa/deltaspike-data/pax-jpa one

**Comment by garyhodgson** [comment]
I'd certainly be interested in seeing this implemented. 

I have made a start trying to use deltaspike repository with pax-cdi, but so far haven't been able to successfully inject the repository.  (I get a "WELD-001408: Unsatisfied dependencies ..." error at bundle start)

**Comment by Tcharl** [comment]
I will take a look at this, making an itest in the 'features' module, I'll also make a branch for this issue (maybe we must do some more wrappers).

**Comment by Tcharl** [comment]
I made a simple test here: https://github.com/OsgiliathEnterprise/net.osgiliath.parent/tree/master/net.osgiliath.framework/net.osgiliath.features.karaf-features/net.osgiliath.features.karaf-features.itests/net.osgiliath.features.karaf-features.itests.jpa.cdi.data

Unfortunately it's failing with a NPE (so the junit test has been marked @Ignore ).
Just have to investigate a little bit on this (if you have time, or when I'll have).

**Comment by Tcharl** [comment]
A simpler test (without Deltaspike) spawned the same error: https://github.com/OsgiliathEnterprise/net.osgiliath.parent/tree/master/net.osgiliath.framework/net.osgiliath.features.karaf-features/net.osgiliath.features.karaf-features.itests/net.osgiliath.features.karaf-features.itests.jpa.pax

**Comment by Tcharl** [comment]
no more needed: replaced by a combination of blueprint maven plugin and Aries-jpa 2
