### ISSUE TITLE
Issue when compiling net.osgiliath.parent on Windows

### ISSUE THREAD

**Issue by garyhodgson** [OsgiliathEnterprise/net.osgiliath.parent#47]
HI,

I came across a couple of issues when compiling on Windows.

1. The fill-parent-path-property profile adds an extra slash to the parent.path property in build.properties.  This causes erroneous new line in jacoco path  e.g.  ```parent.path = T:\\\workspace\\\Misc\\\net.osgiliath.parent``` will be interpreted as ```T:\workspace\Misc\```.  Even though it's a one-line change I'll create a pull request from my fork in a moment.

2. Windows version of ProcessBuilder (used in pax exam) doesn't appear to handle working directories with a path longer then 256 characters. e.g. the following is 261 chars and threw an error: "CreateProcess error=267, The directory name is invalid" ```T:\workspace\Misc\net.osgiliath.parent\net.osgiliath.framework\net.osgiliath.features.karaf-features\net.osgiliath.features.karaf-features.itests\net.osgiliath.features.karaf-features.itests.validation.cdi\target\exam\unpack\36076278-1678-4425-8fe0-918b0bd47a98```

    Renaming my "net.osgiliath.parent" folder to "osgiliath" fixed the problem.   I can't see a way to remedy this, but perhaps a note in the docs might save someone time in the future.

Best regards.

**Comment by Tcharl** [comment]
You can Edit the gh-pages branch if you want, or I can do it so...

Thank you for thiese pointers ;)

**Comment by Tcharl** [comment]
Documentation updated: http://osgiliathenterprise.github.io/projects.documentations/documentations/osgiliath-enterprise-framework/gettingstarted.html#very_quickstart
